export const facultyData = {
  teaching: [
    {
      id: 'faculty-1',
      name: 'Dr. Bhaskara Raju Vatchavai',
      qualification: 'M.Pharm., Ph.D.',
      designation: 'Professor & Principal',
      profile: '/public/uploads/pdfs/faculty/1.pdf',
    },
    {
      id: 'faculty-2',
      name: 'Dr. P. Narayana Raju',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Professor & HOD',
      profile: '/public/uploads/pdfs/faculty/2.pdf',
    },
    {
      id: 'faculty-3',
      name: 'Dr. Y. B. Manjulatha',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Professor & HOD',
      profile: '/public/uploads/pdfs/faculty/3.pdf',
    },
    {
      id: 'faculty-4',
      name: 'Dr. X. Antro Jennie',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Professor & HOD',
      profile: '/public/uploads/pdfs/faculty/4.pdf',
    },
    {
      id: 'faculty-5',
      name: 'Dr. M. Srinivasu',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Professor & HOD',
      profile: '/public/uploads/pdfs/faculty/5.pdf',
    },
    {
      id: 'faculty-6',
      name: 'Dr. N. Shiva Kumar',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/6.pdf',
    },
    {
      id: 'faculty-7',
      name: 'Mr. P. Rambabu',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/7.pdf',
    },
    {
      id: 'faculty-8',
      name: 'Mr. Dhabal Kumar Satapathy',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/8.pdf',
    },
    {
      id: 'faculty-9',
      name: 'Mr. S. Sumanth Kantham',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/9.pdf',
    },
    {
      id: 'faculty-10',
      name: 'Mrs. K. Kalyani',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/10.pdf',
    },
    {
      id: 'faculty-11',
      name: 'Mrs. M. Sharmila',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/11.pdf',
    },
    {
      id: 'faculty-12',
      name: 'Mrs. B. Vijaya Ambica Durga',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/12.pdf',
    },
    {
      id: 'faculty-13',
      name: 'Mr. J. N. B. Indu Sekhar',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/13.pdf',
    },
    {
      id: 'faculty-14',
      name: 'Ms. V. P. Praneetha',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/14.pdf',
    },
    {
      id: 'faculty-15',
      name: 'Ms. P. Esther',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/15.pdf',
    },
    {
      id: 'faculty-16',
      name: 'Mr. M. Ajay Rathnam',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/16.pdf',
    },
    {
      id: 'faculty-17',
      name: 'Mrs. P. Thirupathamma',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/17.pdf',
    },
    {
      id: 'faculty-18',
      name: 'Ms. K. Rajeswari',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/18.pdf',
    },
    {
      id: 'faculty-19',
      name: 'Mrs. D. Bindi',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/19.pdf',
    },
    {
      id: 'faculty-20',
      name: 'Mrs. T. Yamini Kumari',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/20.pdf',
    },
    {
      id: 'faculty-21',
      name: 'Mr. P. Srinu',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/21.pdf',
    },
    {
      id: 'faculty-22',
      name: 'Mrs. A. Durga Pallavi',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/22.pdf',
    },
    {
      id: 'faculty-23',
      name: 'Mrs. B. Pallavi',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/23.pdf',
    },
    {
      id: 'faculty-24',
      name: 'Mrs. V. Sri Sowmya',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/24.pdf',
    },
    {
      id: 'faculty-25',
      name: 'Mr. K. Siva Teja',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/25.pdf',
    },
    {
      id: 'faculty-26',
      name: 'Mr. S. S. S. M. Sharma',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/26.pdf',
    },
    {
      id: 'faculty-27',
      name: 'Ms. P. Sravanthi',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/27.pdf',
    },
    {
      id: 'faculty-28',
      name: 'Ms. G. Lalitha Sarojini',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/28.pdf',
    },
    {
      id: 'faculty-29',
      name: 'Ms. D. Rachel Shalini',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/29.pdf',
    },
    {
      id: 'faculty-30',
      name: 'Mrs. E. Karuna Kumari',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/30.pdf',
    },
  ],
  nonTeaching: [
    {
      id: 'non-teaching-1',
      name: 'Mrs. R. Satyavathi',
      qualification: '',
      designation: 'Office Superintendent',
      profile: '',
    },
    {
      id: 'non-teaching-2',
      name: 'Mr. E. Satyanarayana',
      qualification: '',
      designation: 'Office Clerk',
      profile: '',
    },
    {
      id: 'non-teaching-3',
      name: 'Mr. S.N.S. Venkata Ratnam',
      qualification: '',
      designation: 'Technician',
      profile: '',
    },
    {
      id: 'non-teaching-4',
      name: 'Mr. M. Srinivasa Rao',
      qualification: '',
      designation: 'Technician',
      profile: '',
    },
    {
      id: 'non-teaching-5',
      name: 'Mr. Y. Kameswara Rao',
      qualification: '',
      designation: 'Technician',
      profile: '',
    },
    {
      id: 'non-teaching-6',
      name: 'Mrs. Y. Vijaya Lakshmi',
      qualification: '',
      designation: 'Assistant Librarian',
      profile: '',
    },
    {
      id: 'non-teaching-7',
      name: 'Ms. K. Sai Sravanthi',
      qualification: '',
      designation: 'Lab Technician',
      profile: '',
    },
    {
      id: 'non-teaching-8',
      name: 'Mr. B. Satya Vara Prasad',
      qualification: '',
      designation: 'Lab Technician',
      profile: '',
    },
    {
      id: 'non-teaching-9',
      name: 'Mr. K. Sai Kumar',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-10',
      name: 'Ms. K. Supriya',
      qualification: '',
      designation: 'Library Attender',
      profile: '',
    },
    {
      id: 'non-teaching-11',
      name: 'Mr. K. Satyanarayana',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-12',
      name: 'Ms. U. Mani',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-13',
      name: 'Mr. B.J.R. Prasad',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-14',
      name: 'Mr. M.S.S.N.V.V. Gopal',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-15',
      name: 'Mrs. V. Jyothi',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-16',
      name: 'Ms. Y. Hema Latha',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-17',
      name: 'Mr. V. V. Eswara Rao',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
  ],
  visiting: [
    {
      id: 'visiting-1',
      name: 'Ms. M. Pravallika',
      qualification: 'M-Tech',
      department: 'CSE',
      subjects: 'Computer Applications',
      profile: '/public/uploads/pdfs/faculty/',
    },
    {
      id: 'visiting-2',
      name: 'Ms. P.V. Padmavathi',
      qualification: 'M.A, B.Ed.',
      department: 'BSH',
      subjects: 'English',
      profile: '/public/uploads/pdfs/faculty/31.pdf',
    },
    {
      id: 'visiting-3',
      name: 'Mr. S. K. Dhana Prasad',
      qualification: 'M.Sc., B.Ed.',
      department: 'BSH',
      subjects: 'Bio Stat and Research Methodology',
      profile: '/public/uploads/pdfs/faculty/32.pdf',
    },
    {
      id: 'visiting-4',
      name: 'Mr. S. Veeresh',
      qualification: 'M.Sc., B.Ed.',
      department: 'BSH',
      subjects: 'Bio Stat and Research Methodology',
      profile: '/public/uploads/pdfs/faculty/33.pdf',
    },
  ],
};
